"""
London Weekend Curator
Runs every Saturday evening, searches for 15 things to do in London
the following Fri-Sun, and emails the curated list.
"""

import os
import json
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timedelta
import anthropic


def get_next_weekend_dates() -> tuple[str, str, str]:
    """Returns (friday, saturday, sunday) date strings for the upcoming weekend."""
    today = datetime.now()
    # Find next Friday (weekday 4)
    days_until_friday = (4 - today.weekday()) % 7
    if days_until_friday == 0:
        days_until_friday = 7  # If today is Friday, get next Friday
    # If today is Saturday (running day), next Friday is 6 days away
    if today.weekday() == 5:
        days_until_friday = 6

    next_friday = today + timedelta(days=days_until_friday)
    next_saturday = next_friday + timedelta(days=1)
    next_sunday = next_friday + timedelta(days=2)

    return (
        next_friday.strftime("%A %d %B %Y"),
        next_saturday.strftime("%A %d %B %Y"),
        next_sunday.strftime("%A %d %B %Y"),
    )


def build_prompt(fri: str, sat: str, sun: str) -> str:
    return f"""You are a London weekend curator for someone who lives in Canary Wharf.

Find exactly 15 things to do in London for the weekend of {fri} to {sun}.

The selections MUST cover these categories (aim for roughly 3 each):

- SPORTS: Live sports events, pick-up games, interesting fitness events, spectator sport
- FOOD: New restaurant openings, pop-ups, food markets, supper clubs, notable dining
- CULTURE: Exhibitions, theatre, gigs, comedy, film, talks, literary events
- NEW OPENINGS: Bars, venues, shops, spaces that recently opened or are launching that weekend
- WEIRD / OFFBEAT: Unusual, quirky, surprising, niche, or one-off events — the stranger the better

For each selection provide:
1. Name of the event/venue/experience
2. Category (one of the five above)
3. Date(s) — which day(s) of the weekend
4. Location — specific area of London
5. Why it's worth going — 1-2 sentences, opinionated and concise
6. Link — the most useful URL (event page, booking link, venue site)
7. Price — free, or approximate cost

Format your response as clean HTML suitable for an email body. Use a simple, modern design.
Group by category with clear headers. Include a dark header banner with the weekend dates.
Keep it punchy — no waffle. Tone: a smart friend who knows London well, not a corporate
newsletter. Use emoji sparingly for category headers.

IMPORTANT: Only include events/things genuinely happening on {fri}, {sat}, or {sun}.
Do not fabricate events. If you can't find 3 for a category, redistribute across others
to hit 15 total.
"""


def call_claude(prompt: str) -> str:
    """Call Claude API with web search enabled to find weekend events."""
    client = anthropic.Anthropic()  # Uses ANTHROPIC_API_KEY env var

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        tools=[
            {
                "type": "web_search_20250305",
                "name": "web_search",
                "max_uses": 10,
            }
        ],
        messages=[{"role": "user", "content": prompt}],
    )

    # Extract text content from the response
    text_parts = []
    for block in response.content:
        if block.type == "text":
            text_parts.append(block.text)

    return "\n".join(text_parts)


def extract_html(response_text: str) -> str:
    """Extract HTML content from Claude's response, handling markdown code blocks."""
    if "```html" in response_text:
        start = response_text.index("```html") + 7
        end = response_text.index("```", start)
        return response_text[start:end].strip()
    if response_text.strip().startswith("<"):
        return response_text.strip()
    return f"<div>{response_text}</div>"


def build_email_html(inner_html: str) -> str:
    """Wrap the curator output in a full email template."""
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            max-width: 640px;
            margin: 0 auto;
            padding: 20px;
            background: #f8f8f8;
        }}
        a {{ color: #2563eb; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    {inner_html}
    <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 32px 0 16px;">
    <p style="font-size: 12px; color: #999; text-align: center;">
        Auto-generated by Weekend Curator · Powered by Claude
    </p>
</body>
</html>"""


def send_email(html_content: str, fri: str, sun: str):
    """Send the curated email via Gmail SMTP."""
    sender = os.environ["GMAIL_ADDRESS"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipients = os.environ.get("RECIPIENT_EMAILS", sender).split(",")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Your London Weekend — {fri} to {sun}"
    msg["From"] = f"Weekend Curator <{sender}>"
    msg["To"] = ", ".join(recipients)

    plain = f"Your London weekend picks for {fri} to {sun}. View in HTML for the full experience."
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipients, msg.as_string())

    print(f"Email sent to {', '.join(recipients)}")


def main():
    fri, sat, sun = get_next_weekend_dates()
    print(f"Curating weekend: {fri} — {sun}")

    prompt = build_prompt(fri, sat, sun)
    print("Calling Claude with web search...")

    response = call_claude(prompt)
    html = extract_html(response)
    email_html = build_email_html(html)

    send_email(email_html, fri, sun)
    print("Done!")


if __name__ == "__main__":
    main()
